package com.uelbosque.cjlfactory.model;
// Generated 7/11/2015 03:24:29 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name = "carrera", catalog = "sistema_academico")
public class Carrera {

	private int idCarrera;
	private String nombreCarrera;
	private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

	public Carrera() {
	}

	public Carrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	public Carrera(int idCarrera, String nombreCarrera, Set<Estudiante> estudiantes) {
		this.idCarrera = idCarrera;
		this.nombreCarrera = nombreCarrera;
		this.estudiantes = estudiantes;
	}

	@Id

	@Column(name = "id_carrera", unique = true, nullable = false)
	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	@Column(name = "nombre_carrera", length = 45)
	public String getNombreCarrera() {
		return this.nombreCarrera;
	}

	public void setNombreCarrera(String nombreCarrera) {
		this.nombreCarrera = nombreCarrera;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carrera")
	public Set<Estudiante> getEstudiantes() {
		return this.estudiantes;
	}

	public void setEstudiantes(Set<Estudiante> estudiantes) {
		this.estudiantes = estudiantes;
	}

}
