package com.uelbosque.cjlfactory.model;
// Generated 7/11/2015 03:24:29 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name = "estudiante", catalog = "sistema_academico")
public class Estudiante {

	private Integer idEstudiante;
	private Carrera carrera;
	private String nombresEstudiante;
	private String apellidosEstudiante;
	private String direccionEstudiante;
	private String correoEstudiante;
	private Date fechaNacEstudiante;
	private String lugarNacEstudiante;
	private String telefonoEstudiante;
	private Integer edadEstudiante;
	private String identificacionEstudiante;
	private int idestudiante;
	private String nombre;
	private String apellidos;
	private Date fechanacimiento;
	private String lugarnacimiento;
	private String telefono;
	private String direccion;
	private String correoelectronico;
	private Set<EstudianteMateria> estudianteMaterias = new HashSet<EstudianteMateria>(0);
	private Set<EstudianteMateria> estudianteMaterias_1 = new HashSet<EstudianteMateria>(0);

	public Estudiante() {
	}

	public Estudiante(int idestudiante) {
		this.idestudiante = idestudiante;
	}

	public Estudiante(Carrera carrera, String nombresEstudiante, String apellidosEstudiante, String direccionEstudiante,
			String correoEstudiante, Date fechaNacEstudiante, String lugarNacEstudiante, String telefonoEstudiante,
			Integer edadEstudiante, String identificacionEstudiante, int idestudiante, String nombre, String apellidos,
			Date fechanacimiento, String lugarnacimiento, String telefono, String direccion, String correoelectronico,
			Set<EstudianteMateria> estudianteMaterias, Set<EstudianteMateria> estudianteMaterias_1) {
		this.carrera = carrera;
		this.nombresEstudiante = nombresEstudiante;
		this.apellidosEstudiante = apellidosEstudiante;
		this.direccionEstudiante = direccionEstudiante;
		this.correoEstudiante = correoEstudiante;
		this.fechaNacEstudiante = fechaNacEstudiante;
		this.lugarNacEstudiante = lugarNacEstudiante;
		this.telefonoEstudiante = telefonoEstudiante;
		this.edadEstudiante = edadEstudiante;
		this.identificacionEstudiante = identificacionEstudiante;
		this.idestudiante = idestudiante;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechanacimiento = fechanacimiento;
		this.lugarnacimiento = lugarnacimiento;
		this.telefono = telefono;
		this.direccion = direccion;
		this.correoelectronico = correoelectronico;
		this.estudianteMaterias = estudianteMaterias;
		this.estudianteMaterias_1 = estudianteMaterias_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_estudiante", unique = true, nullable = false)
	public Integer getIdEstudiante() {
		return this.idEstudiante;
	}

	public void setIdEstudiante(Integer idEstudiante) {
		this.idEstudiante = idEstudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_carrera")
	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	@Column(name = "nombres_estudiante", length = 45)
	public String getNombresEstudiante() {
		return this.nombresEstudiante;
	}

	public void setNombresEstudiante(String nombresEstudiante) {
		this.nombresEstudiante = nombresEstudiante;
	}

	@Column(name = "apellidos_estudiante", length = 45)
	public String getApellidosEstudiante() {
		return this.apellidosEstudiante;
	}

	public void setApellidosEstudiante(String apellidosEstudiante) {
		this.apellidosEstudiante = apellidosEstudiante;
	}

	@Column(name = "direccion_estudiante", length = 45)
	public String getDireccionEstudiante() {
		return this.direccionEstudiante;
	}

	public void setDireccionEstudiante(String direccionEstudiante) {
		this.direccionEstudiante = direccionEstudiante;
	}

	@Column(name = "correo_estudiante", length = 50)
	public String getCorreoEstudiante() {
		return this.correoEstudiante;
	}

	public void setCorreoEstudiante(String correoEstudiante) {
		this.correoEstudiante = correoEstudiante;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_nac_estudiante", length = 19)
	public Date getFechaNacEstudiante() {
		return this.fechaNacEstudiante;
	}

	public void setFechaNacEstudiante(Date fechaNacEstudiante) {
		this.fechaNacEstudiante = fechaNacEstudiante;
	}

	@Column(name = "lugar_nac_estudiante", length = 45)
	public String getLugarNacEstudiante() {
		return this.lugarNacEstudiante;
	}

	public void setLugarNacEstudiante(String lugarNacEstudiante) {
		this.lugarNacEstudiante = lugarNacEstudiante;
	}

	@Column(name = "telefono_estudiante", length = 25)
	public String getTelefonoEstudiante() {
		return this.telefonoEstudiante;
	}

	public void setTelefonoEstudiante(String telefonoEstudiante) {
		this.telefonoEstudiante = telefonoEstudiante;
	}

	@Column(name = "edad_estudiante")
	public Integer getEdadEstudiante() {
		return this.edadEstudiante;
	}

	public void setEdadEstudiante(Integer edadEstudiante) {
		this.edadEstudiante = edadEstudiante;
	}

	@Column(name = "identificacion_estudiante", length = 20)
	public String getIdentificacionEstudiante() {
		return this.identificacionEstudiante;
	}

	public void setIdentificacionEstudiante(String identificacionEstudiante) {
		this.identificacionEstudiante = identificacionEstudiante;
	}

	@Column(name = "idestudiante", nullable = false)
	public int getIdestudiante() {
		return this.idestudiante;
	}

	public void setIdestudiante(int idestudiante) {
		this.idestudiante = idestudiante;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos")
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechanacimiento", length = 10)
	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@Column(name = "lugarnacimiento")
	public String getLugarnacimiento() {
		return this.lugarnacimiento;
	}

	public void setLugarnacimiento(String lugarnacimiento) {
		this.lugarnacimiento = lugarnacimiento;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "correoelectronico")
	public String getCorreoelectronico() {
		return this.correoelectronico;
	}

	public void setCorreoelectronico(String correoelectronico) {
		this.correoelectronico = correoelectronico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudiante")
	public Set<EstudianteMateria> getEstudianteMaterias() {
		return this.estudianteMaterias;
	}

	public void setEstudianteMaterias(Set<EstudianteMateria> estudianteMaterias) {
		this.estudianteMaterias = estudianteMaterias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudiante")
	public Set<EstudianteMateria> getEstudianteMaterias_1() {
		return this.estudianteMaterias_1;
	}

	public void setEstudianteMaterias_1(Set<EstudianteMateria> estudianteMaterias_1) {
		this.estudianteMaterias_1 = estudianteMaterias_1;
	}

}
