package com.uelbosque.cjlfactory.model;
// Generated 7/11/2015 03:24:29 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EstudianteMateria generated by hbm2java
 */
@Entity
@Table(name = "estudiante_materia", catalog = "sistema_academico")
public class EstudianteMateria {

	private Integer idEstudianteMateria;
	private Estudiante estudiante;
	private Integer idMateria;
	private Integer nota1Materia;
	private Integer nota2Materia;
	private Integer nota3Materia;

	public EstudianteMateria() {
	}

	public EstudianteMateria(Estudiante estudiante, Integer idMateria, Integer nota1Materia, Integer nota2Materia,
			Integer nota3Materia) {
		this.estudiante = estudiante;
		this.idMateria = idMateria;
		this.nota1Materia = nota1Materia;
		this.nota2Materia = nota2Materia;
		this.nota3Materia = nota3Materia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_estudiante_materia", unique = true, nullable = false)
	public Integer getIdEstudianteMateria() {
		return this.idEstudianteMateria;
	}

	public void setIdEstudianteMateria(Integer idEstudianteMateria) {
		this.idEstudianteMateria = idEstudianteMateria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estudiante")
	public Estudiante getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(Estudiante estudiante) {
		this.estudiante = estudiante;
	}

	@Column(name = "id_materia")
	public Integer getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(Integer idMateria) {
		this.idMateria = idMateria;
	}

	@Column(name = "nota1_materia", precision = 5, scale = 0)
	public Integer getNota1Materia() {
		return this.nota1Materia;
	}

	public void setNota1Materia(Integer nota1Materia) {
		this.nota1Materia = nota1Materia;
	}

	@Column(name = "nota2_materia", precision = 5, scale = 0)
	public Integer getNota2Materia() {
		return this.nota2Materia;
	}

	public void setNota2Materia(Integer nota2Materia) {
		this.nota2Materia = nota2Materia;
	}

	@Column(name = "nota3_materia", precision = 5, scale = 0)
	public Integer getNota3Materia() {
		return this.nota3Materia;
	}

	public void setNota3Materia(Integer nota3Materia) {
		this.nota3Materia = nota3Materia;
	}

}
