package com.uelbosque.cjlfactory.model;
// Generated 7/11/2015 03:24:29 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name = "materia", catalog = "sistema_academico")
public class Materia {

	private Integer idMateria;
	private String nombreMateria;
	private Integer creditosMaterias;

	public Materia() {
	}

	public Materia(String nombreMateria, Integer creditosMaterias) {
		this.nombreMateria = nombreMateria;
		this.creditosMaterias = creditosMaterias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_materia", unique = true, nullable = false)
	public Integer getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(Integer idMateria) {
		this.idMateria = idMateria;
	}

	@Column(name = "nombre_materia", length = 50)
	public String getNombreMateria() {
		return this.nombreMateria;
	}

	public void setNombreMateria(String nombreMateria) {
		this.nombreMateria = nombreMateria;
	}

	@Column(name = "creditos_materias")
	public Integer getCreditosMaterias() {
		return this.creditosMaterias;
	}

	public void setCreditosMaterias(Integer creditosMaterias) {
		this.creditosMaterias = creditosMaterias;
	}

}
